spring:
  application:
    name: scheduler-base

  datasource:
    url: jdbc:sqlserver://192.168.1.196:1433;databaseName=UVICAR_0;encrypt=true;trustServerCertificate=true
    username: sa
    password: "SofTrack*9278"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info

jobs:
  timezone: America/Lima
  sample:
    every5min-cron: "0 */5 * * * *"
    twiceDaily-cron: "0 0 9,18 * * *"
